name: 'Discord Webhook Alert'
description: 'Discord webhook for Github deployment'
inputs:
  webhookUrl:
    description: Discord webhook URL. Should be stored in a secret and inserted as a context expression.
    required: true
  type:
    description: Type - success, warn, or error
    required: false
    default: error
  name:
    description: Webhook name
    required: false
  avatar:
    description: Webhook avatar
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'