name: 'Discord Webhook Alert'
description: 'Discord webhook for Github deployment'
inputs:
  webhookUrl:
    description: Discord webhook URL. Should be stored in a secret and inserted as a context expression.
    required: true
  type:
    description: Type - success, warn, or error
    required: true
    default: error
  project:
    description: Project name
    required: false
  message:
    description: Custom Message for succes or error (Default message\:\ "Deployment on stage \##\repository\##\ \##\state\##\.")
    required: false
  name:
    description: Webhook name
    required: false
  avatar:
    description: Webhook avatar
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'