name: Notify

on:
  workflow_dispatch:
    inputs:
      webhook:
        description: "Webhook Url"
        required: true
      type:
        description: "type alert"
        required: true
      project:
        description: "Project name"
        required: false
      name:
        description: "Name alert"
        required: false
      avatar:
        description: "Avatar alert"
        required: false
      message:
        description: "Custom Message"
        required: false

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Alert
        uses: LeoCpii/discord-webhook-alert@master
        with:
          webhookUrl: ${{ inputs.webhook }}
          type: ${{ inputs.type }}
          project: ${{ inputs.project }}
          name: ${{ inputs.name }}
          avatar: ${{ inputs.avatar }}
          message: ${{ inputs.message }}
          
